# Generated by Django 3.2.7 on 2025-10-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(blank=True, max_length=100, null=True)),
                ('productprice', models.CharField(blank=True, max_length=100, null=True)),
                ('profile', models.ImageField(upload_to='profile/')),
            ],
        ),
    ]
