# Generated by Django 3.2.7 on 2025-10-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='carpenter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
