# Generated by Django 3.2.7 on 2025-10-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_user_carpenter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carpenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carpenter', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='carpenter',
        ),
    ]
