# Generated by Django 3.2.7 on 2025-10-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_customisedproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colorname', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='profile/')),
            ],
        ),
        migrations.DeleteModel(
            name='Carpenter',
        ),
    ]
