# Generated by Django 3.2.7 on 2025-10-23 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20251023_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colour',
            old_name='colorname',
            new_name='colourname',
        ),
    ]
