# Generated by Django 3.2.7 on 2025-10-29 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customisedorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.category')),
                ('colour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.colour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.wood')),
            ],
        ),
        migrations.DeleteModel(
            name='Customisedproduct',
        ),
    ]
