# Generated by Django 3.2.7 on 2025-11-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productprice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
