# Generated by Django 3.2.7 on 2025-11-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_alter_product_productprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
